service: liff-test

# 実行環境に関する設定
provider:
  name: aws
  runtime: nodejs8.10
  region: ap-northeast-1
  profile: giboshi31

# 利用するプラグインについて
plugins:
  - serverless-offline

# デプロイ時のパッケージの内容について
# package:
#   include:
#     - src/**

functions:
  webhook:
    handler: messageIndex.handler
    events:
      - http:
          path: /webhook
          method: post
          cors: true
  openLiff:
    handler: liffIndex.handler
    events:
      - http:
          path: /liff
          method: get
          cors: true
  saveImage:
    handler: liffIndex.handler
    events:
      - http:
          path: /saveimage
          method: post
          cors: true
# resources:
#   Resources:
#     S3BucketImages:
#       Type: AWS::S3::Bucket
#       Properties:
#         BucketName: drawing-telephone-game-linebot-images